### ISSUE TITLE
Cannot read property 'OutputValue' of undefined

### ISSUE THREAD

**Issue by craigmonson** [matt-filion/serverless-external-s3-event#25]
Node Version: 8.1.0
Serverless Version: 1.17.0
serverless-external-s3-event: 1.7 (from npm)

Running in the node:8.1.0-alpine container

```
%> docker run -itP -v ... -v ... -e SLS_DEBUG=true serverless-test s3deploy

  Type Error ---------------------------------------------

  Cannot read property 'OutputValue' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'OutputValue' of undefined
    at bucket.NotificationConfiguration.LambdaFunctionConfigurations.forEach (/node_modules/serverless-external-s3-event/index.js:88:27)
    at Array.forEach (native)
    at bucketNotifications.forEach (/node_modules/serverless-external-s3-event/index.js:81:71)
    at Array.forEach (native)
    at info.getStackInfo.then (/node_modules/serverless-external-s3-event/index.js:79:27)
From previous event:
    at S3Deploy.afterS3DeployFunctions (/node_modules/serverless-external-s3-event/index.js:73:32)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:32:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.1.0
     Serverless Version:     1.17.0
```

serverless.yaml:
```
service: "blahblah-decider"

custom:
  devBucket: "blahblah-config-log-dev"
  prodBucket: "blahblah-config-log"
  bucketValue: "${self:custom.${opt:stage, self:provider.stage}Bucket}"

plugins:
  - serverless-external-s3-event

provider:
  name: "aws"
  runtime: "python2.7"
  stage: "dev"
  region: "us-west-2"
  versionFunctions: false
  stackTags:
    DeploymentMethod: "Serverless - blahblah-decider"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource: arn:aws:s3:::${self:custom.bucketValue}

functions:
  decide:
    handler: handler.Decide
    events:
      - existingS3:
          bucket: ${self:custom.bucketValue}
          events:
            - s3:ObjectCreated:*

resources:
  Resources:
  Outputs:
    bucketValue:
      Description: "bucketValue"
      Value: ${self:custom.bucketValue}

**Comment by dkotvan** [comment]
@craigmonson I was having the same problem too when I changed versionFunctions to false. After changing the versionFunctions back to true it started to work again.
