### ISSUE TITLE
eventTypes.join is not a function

### ISSUE THREAD

**Issue by chunkya** [matt-filion/serverless-external-s3-event#54]
After running sls deploy, I try to run sls s3deploy and I get an error. 

Node version: 10.0.0
serverless-plugin-existing-s3: 2.1.0

Here is the stacktrace.
```
Boons-MacBook-Pro:testing booneng$ sls s3deploy
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command s3deploy
Serverless: Invoke s3deploy
Serverless: beforeFunctions --> building ... 
Serverless: beforeFunctions <-- Complete, built 1 events.
Serverless: functions --> prepare to be executed by s3 buckets ... 
policyId exS3-v2-s3-to-elasticsearch2-trendbox
Serverless: functions <-- built 0 events across 1 buckets. 
Serverless: beforeS3 --> 
Serverless: beforeS3 <-- 
Serverless: s3 --> initiate requests ...
 
  Type Error ---------------------------------------------
 
  eventTypes.join is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: eventTypes.join is not a function
    at S3.getId (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/S3.js:15:51)
    at BucketConfig.isNew (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/BucketConfig.js:32:22)
    at fileConfig.events.forEach (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/BucketConfig.js:27:16)
    at Array.forEach (<anonymous>)
    at BucketConfig.addNewNotifications (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/BucketConfig.js:26:23)
    at BucketConfig.update (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/BucketConfig.js:21:10)
    at promises.bucketNotifications.map.bucketConfigurationFromFile (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/index.js:151:24)
    at Array.map (<anonymous>)
    at S3Deploy.s3 (/Users/booneng/Desktop/testing/node_modules/serverless-plugin-existing-s3/index.js:145:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.0.0
     Serverless Version:     1.26.1
```

**Comment by a1anw2** [comment]
I am still getting this error and i am running the latest plugin

**Comment by alexdorandmec** [comment]
I am still experiencing this issue

**Comment by alexdorandmec** [comment]
Opened another bug, since this is not fixed: https://github.com/matt-filion/serverless-external-s3-event/issues/67
