### ISSUE TITLE
Permissions.js#L36: policy might be undefined

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [matt-filion/serverless-external-s3-event#59]
https://github.com/matt-filion/serverless-external-s3-event/blob/e87bc09020abd6cb7abd7d14c955f8fdc58f2fe1/Permissions.js#L36

I have recently seen that I am getting an error where it appears that policy is undefined, causing this error;

```
TypeError: Cannot read property 'Statement' of undefined
    at LambdaPermissions.getStatement (/Users/myProject/node_modules/serverless-plugin-existing-s3/Permissions.js:36:19)
    at provider.request.then.results (/Users/myProject/node_modules/serverless-plugin-existing-s3/Permissions.js:24:61)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at LambdaPermissions.createPolicy (/Users/myProject/node_modules/serverless-plugin-existing-s3/Permissions.js:24:8)
    at results.map.result (/Users/myProject/node_modules/serverless-plugin-existing-s3/index.js:94:41)
    at Array.map (<anonymous>)
    at Promise.all.then.results (/Users/myProject/node_modules/serverless-plugin-existing-s3/index.js:70:33)
    at <anonymous>
```

I don't really know the root cause of this, but perhaps it could be solved by doing something like this:

```
if(policy && policy.Statement){
  return policy.Statement.find( statement => statement.Sid === policyId );
} else {
  return {} // or perhaps no else statement, causing it to return undefined?
}
```

**Comment by matt-filion** [comment]
Without knowing the cause It would be to risky to add a fix in. Can you provide a serverless.yml showing the failure?

This issue is quite old and likely stale, if I dont get a response in a week or so I'll close it.
